site_name: Innovation Lab

theme:
  name: material
  font:
    text: Source Sans Pro
    code: Roboto Mono
  palette: 
    - scheme: default
      # primary: teal
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate 
      # primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  # highlightjs: true
  # hljs_languages:
  #     - python
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - toc.follow
    - content.code.annotate
  markdown_extentions:
    - pymdownx.highlight:
        anchor_linenums: false


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - 'javascripts/headroom.js'
  - 'javascripts/activate_headroom.js'


plugins:
  - search:
      lang: en

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Readings:
    - readings/index.md
  - Blog: 
    - blog/index.md
    - 2022:
      - blog/2022/github-pages-mkdocs.md
  - Life Style:
    - lifestyle/index.md