site_name: Innovation Lab
copyright: 'Copyright &copy; 2022 Fei Wang'
repo_url: https://github.com/oceanumeric/oceanumeric.github.io

nav:
  - Home: index.md
  - Readings:
    - readings/index.md
    - 2022:
      - readings/2022/innovation-research-roadmap.md
  - Blog: 
    - blog/index.md
    - 2022:
      - blog/2022/github-pages-mkdocs.md
      - blog/2022/jupyter-notebook-mkdocs.md
  - LifeStyle:
    - lifestyle/index.md
    - food:
      - lifestyle/food/balanced-diet.md
  - Mathematics:
    - math/index.md
    - probability:
      - math/prob/history-probability.md
      - math/prob/generating-function.ipynb

theme:
  name: material
  icon:
    logo: fontawesome/brands/connectdevelop
  favicon: images/innovation.png
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    - scheme: default
      # primary: teal
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate 
      # primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  # highlightjs: true
  # hljs_languages:
  #     - python
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    # - navigation.sections
    - navigation.expand
    - toc.follow
    - content.code.annotate
  markdown_extentions:
    - pymdownx.highlight:
        anchor_linenums: false
  

edit_uri: ""

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/headroom.js
  - javascripts/activate_headroom.js


plugins:
  - search:
      lang: en
  - tags
  # - git-revision-date
  - git-revision-date-localized:
       type: date
       exclude:
         - index.md
       locale: en
       fallback_to_build_date: true
       enable_creation_date: false
  - mkdocs-jupyter
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      js_files:
          - javascripts/mathjax.js
          - javascripts/headroom.js
          - javascripts/activate_headroom.js
      css_files:
          - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      # permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: oceanumeric
      repo: oceanumeric.github.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

