site_name: Innovation Lab

theme:
  name: material
  font:
    text: Source Sans Pro
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    # - toc.follow

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - 'javascripts/headroom.js'
  - 'javascripts/activate_headroom.js'

markdown_extensions:
  - attr_list
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - toc:
      toc_depth: 2

plugins:
  - search:
      lang: en

nav:
  - Home: index.md
  - Readings:
    - readings/index.md
  - Blog:
    - 2022:
      - blog/2022/github-pages-mkdocs.md
  - Life Style:
    - lifestyle/index.md